[[redirects]]
  from = "/home"
  to = "/index.html"
  status = 200
  force = true

[build]
  command = "npm run build"
  publish = "dist/"
  function = "functions" # keep this committed in the repo
  # functions = "dist/api" # keep this active in dev

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
